'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  辞書編集ダイアログ
        '''
        '''&quot;文字列&quot;とその&quot;読み仮名&quot;を登録してください
        '''文中に同じものがあれば置換するので、どちらも漢字に限らず、送り仮名つきも、登録できます
        '''文書に何度も出てくる語で変換を誤る場合に登録してください
        '''また、読み取りで同じように誤認識する場合は
        '''それを登録してかな変換時に修正数方法もかんがえられます
        '''コピー&amp;ペーストを使う場合はセル全体ではなく文字列が反転している状態の時に
        '''マウス右ボタンを押してください
        '''タイトル行の下のツールバーボタン カット/コピー/貼り付けボタン は行の複写、移動に使います
        '''&quot;貼り付け&quot;は選択行の前に挿入されます(削除フラグはコピーされません)
        '''
        '''&quot;有効&quot; のチェックがあるものが 変換に使用されます
        '''辞書登録の文字列が置換されたあとに漢字かな変換がおこなわれます
        '''置換は表示の順に適用されます、例の&quot;本町&quot;と&quot;町&quot;のように
        '''読みが違う場合はその順番に注意してください
        '''分かち書きの必要な頻出語にも利用できます
        '''
        '''&quot;読み仮名&quot;を指定しないと&quot;(null)&quot;と表示され、変換時に
        '''その&quot;文字列&quot;は削除されます
        '''また&quot;読み仮名&quot;に空白文字を指定 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form11() As String
            Get
                Return ResourceManager.GetString("help_form11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Edit Dictionary Dialog
        '''
        '''Register &quot;String&quot; and corresponding Kana translation.
        '''Simply replace the left column string to right colomun string,
        '''both can contain any type of character.
        '''Register those words repeatedly used in the document, which is not translated correctly.
        '''Those chars extraction mis-rcognize many times may be register and corrected at 
        '''kana translation.
        '''
        '''Use Mouse Right button for Copy &amp; Paste
        '''not when cell is highlightened but when string is highlightened.
        '''Cut/CopyPaste buttons bell [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form11E() As String
            Get
                Return ResourceManager.GetString("help_form11E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form12) 
        '''点訳作法を考慮:
        '''  イメージ読み取りファイルからかな変換ファイルを生成するときに
        '''  以下の処理を行います
        '''  完全な対応は難しいのであとはBES99で対応してください
        '''
        '''    ・3文字以上漢字が連続する場合前にスペースをいれる
        '''    ・漢字ー＞かな変換で発生した、&quot;ゅ&quot;と&quot;ょ&quot;のあとの&quot;う&quot;は&quot;ー&quot;(長音)にかえる
        '''      他にも&quot;う&quot;の代わりに&quot;ー&quot; を使う場合は多いがあとは
        '''      辞書登録するか、上記の変換キーを使用するか、
        '''      あとは BES99上で変更してください
        '''    ・次の文字の後ろに２スペースを入れる
        '''        句点(。）
        '''    ・次の文字の後ろに１スペースを入れる
        '''      読点(、)、中点(・)、疑問符(？)、感嘆符(！)
        '''    ・次の踊り字は元の文字に置き換える
        '''      々 ゝ ゞ ヽ ヾ
        '''
        '''カタカナ文書:
        '''  かな変換用のオプションです
        '''  古い文書で仮名にカタカナを使用している場合にチェックONにしてください
        '''  ONのとき&quot;点字作法を考慮&quot;オプションは影響しませんが
        '''  OFF [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form12() As String
            Get
                Return ResourceManager.GetString("help_form12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form12E) 
        '''
        '''Consideration for translation into Braille:
        '''  Following consideration is done when translation of Japanese Kanji text to Kana text.
        '''  It&apos;s rule is too hard to implement, so correct remainings on BES99.
        '''    .Put space before continued(&gt;=3) kanji chars.
        '''    .After Kanji-&gt;kana translation, replace &quot;う&quot; by &quot;ー&quot;(Choon:long sound)
        '''     if &quot;ー&quot; is next of &quot;ゅ&quot; or &quot;ょ&quot; &quot;.
        '''     In other case &quot;う&quot; have to be replaced by &quot;ー&quot;, use  Translation key above,
        '''     register to dictionary or update on BES99.
        '''  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form12E() As String
            Get
                Return ResourceManager.GetString("help_form12E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  語句定義ダイアログ
        '''
        '''頻出する語句のショートカットキーを登録します
        '''例えば、&quot;三&quot; を &quot;一二&quot; と読む、&quot;禅&quot;と&quot;褝&quot;を取り違えるなど
        '''イメージ読み取りで誤認識が頻発するとき
        '''&quot;三&quot;、&quot;禅&quot;を登録すれば簡単に修正入力できます
        '''
        '''ダイアログは読み取り画面とかなテキスト画面で共通です
        '''その両方を画面を開いているときは、語句定義ダイアログキー(省略値:F9)を押せば
        '''スィッチします。ダイアログの画面の色でどちらへの入力となるか判別できます
        '''&quot;転送先変更&quot; ボタンを押してもスイッチできます
        '''--------------------------------------------------------------------------
        '''&quot;キー&quot;(英字1文字) を指定すると &quot;有効&quot; がチェックしていれば Ctrl+英字で 
        '''ダイアログが開いてない状態でも&quot;語句&quot; をテキストボックスに転送します
        '''キーの英字の大文字小文字は区別されません、重複があると前の行が適用されます
        '''ダイアログを開いているときは &quot;転送&quot; ボタンで &quot;有効&quot;/&quot;削除&quot;の設定にかかわらず転送できます
        '''尚、Ctrl+ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form13() As String
            Get
                Return ResourceManager.GetString("help_form13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Words Definition Dialog
        '''
        '''Register those &quot;Phrase&quot; frequently appear in the document.
        '''A candidate is kanji character sometimes misrecognition occurs
        '''at extracting from image.
        '''e.g. &quot;三&quot; is sometime recognized  as &quot;一&quot; and &quot;二&quot;, 
        '''    &quot;禅&quot; resembles &quot;褝&quot;.
        '''     so register &quot;三&quot; or &quot;禅&quot; to easy correction.
        '''
        '''One dialog supports both of Extracted text form and kana text form.
        '''You can swith forms to receive by Open Key(Default:F9).
        '''Dialog back-color also switches to identify &quot;Phrase&quot; is sent to.
        '''&quot;SwitchFormSendT [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form13E() As String
            Get
                Return ResourceManager.GetString("help_form13E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号入力ダイアログ
        '''
        '''  引用符、括弧など IME変換を介さずに入力する場合に使用します
        '''
        '''  読み取り画面とかな変換画面で共通です
        '''  両画面を開いているときは、記号入力ダイアログキー(省略値:F6)で
        '''  スィッチします。ダイアログの画面の色でどちらへの入力となるか判別できます
        '''  &quot;転送先変更&quot; ボタンを押してもスイッチできます
        '''--------------------------------------------------------------------------
        '''  &quot;転送&quot; を押すとその行の&quot;文字&quot;が読み取り画面またはかな変換画面の
        '''  カーソル位置にセットされます
        '''  キー(1桁数字 &quot;0&quot;～&quot;9&quot;) を設定すればダイアログを開いていない状態でも
        '''  Ctrl+0～Ctrl+9 キーで入力できます
        '''
        '''  タイトル行の下のツールバーボタン オープン/保存/別名保存 は文書ごとに
        '''  記号定義を取り換えて使用したい場合に使用します
        '''  記号ファイルの形式は各行以下のようにします。改行コードは0x0d0aです
        '''  拡張子の省略値は .sym です
        '''  各行 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form14() As String
            Get
                Return ResourceManager.GetString("help_form14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Symbol Input Dialog
        '''  Input Quotation, Parenthesis, ... not by IME.
        '''
        '''  One dialog for both ExtractedText and KanaText form.
        '''  When both Form is opened, use &quot;Open Symbol dialog&quot; key(Default:F6)
        '''  to switch Forms to be received.
        '''  Dialog back-color also switches to identify the symbol is sent to.
        '''  &quot;SwitchFormSendTo&quot; button also enable it.
        '''--------------------------------------------------------------------------
        '''  Push &quot;Send&quot; button to send &quot;String&quot; of the line
        '''  to cursor position of the Extracted [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form14E() As String
            Get
                Return ResourceManager.GetString("help_form14E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  マウスドラッグで囲んだ部分の読み取りテキストです
        '''
        '''カット＆ペーストでメインフォームに取り込んでください
        '''OKボタンはマウスで反転した部分を、反転してなければ全体を
        '''メインフォームのテキストボックスに送ります
        '''送り先はメインフォーム上であらかじめ設定したカーソル位置に
        '''挿入されます
        '''送り先でマウスで反転しておけばその部分が置換されます
        '''
        '''(Form15) 2018/03/04
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form15() As String
            Get
                Return ResourceManager.GetString("help_Form15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Partially extracted Text in the clipped Box.
        '''
        '''Copy then Paste to Main form.
        '''Or, OK button sends all text or reversed part to the Main form.
        '''Set caret at insert position on target form in advance by mouse.
        '''If taret is reversed the range will be replaced.
        '''
        '''(Form15E) 2018/03/04
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_Form15E() As String
            Get
                Return ResourceManager.GetString("help_Form15E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Kana text dialog
        '''
        '''By &quot;TextExtraction function&quot; + &quot;Kana translation function&quot;,
        '''generate Japanese Kana file for WinBES99 extracting text from document file
        '''created by scanner device.
        '''English Document can be extracted, and &quot;Kana translation&quot; do nothing paticularly.
        '''
        '''Kana is a collection of Japanese Letter excludes Kanji.
        '''WinBES99 is a text translation tool into Braille.
        '''Windows app &quot;Windows Fax and Scan&quot; can be used to create image file. 
        '''
        '''Requirement：Extrancting text from image file uses &quot;Microsoft [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form1E() As String
            Get
                Return ResourceManager.GetString("help_form1E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文書読み取り機能＋かな変換機能で
        '''スキャナーで読み取ったイメージファイルから漢字かな混じり文を読み取って
        '''WinBES99 のためのかな入力ファイルを作成するツールです
        '''イメージファイルは &quot;Windows Fax と スキャン&quot; で スキャナーからイメージファイルを得ることができます
        '''英語文書も読み取れますが&quot;かな変換&quot;では特になにもしません
        '''
        '''要件：文書読み取り機能は &quot;Microsoft OCR Library for Windows&quot; を使用しています
        '''      Windows10 Novenber Update(2015/11:Version 1511)にアップグレードが必要です
        '''
        '''メニューの &quot;ファイル&quot; ー＞ &quot;イメージファイルを開く&quot; から始め
        '''イメージファイル画面で &quot;読み取り&quot;ーー＞
        '''テキストファイル画面で &quot;かな変換&quot;ーー＞
        '''で、この画面にかなテキストファイルが表示されます
        '''
        '''長い行は折り返し表示されます
        '''&quot;Enter&quot;キーで行が分割され、改行マーク(⏎)の
        '''削除で行が連結されます
        '''
        '''半角カタカナは
        '''イメージ読み取りファイルから &quot;かな変換&quot; した [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form1U8() As String
            Get
                Return ResourceManager.GetString("help_form1U8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージファイルが表示されています
        '''
        '''&quot;1°&quot;:
        '''  オン(黄色)にすると回転ボタンで１度づつ回転されます
        '''  少しだけ傾いた画像を読み取るときに使用します
        '''
        '''&quot;読み取り&quot;:
        '''  読み取り結果が別のテキストフォームに表示されます
        '''  読み取りには多少時間がかかります
        '''  元の画像の解像度で読み取りをしているのでズームは読み取りに影響しませんが
        '''  イメージの上下は影響します、回転をしてください
        '''  読み取れた場所はマーク表示されます
        '''
        '''  縦書き横書き混じりの文書の場合など、
        '''  縦書き文書を横読みすることがあります
        '''  読めなかった部分はマウスドラッグで青線で囲んで
        '''  その部分だけ読み取りすることもできます
        '''  ボックスはマウスクリックすると消えます
        '''
        '''  部分読み取りすると結果が別のフォームに表示されます
        '''  OKボタンまたはカット＆ペーストで取り込んでください
        '''
        '''&quot;言語&quot;:
        '''  横書き、縦書きの判定は Windows OCR Library が行うので
        '''  Library に対する指定はできませんが左右のページを逆に認識することがあります
        '''  この指定 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form2() As String
            Get
                Return ResourceManager.GetString("help_form2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Displaying document image file
        '''
        '''&quot;1°&quot;:
        '''  When On(Yellow), rotate by one degree.
        '''  Use for image with a litte slope.
        '''
        '''&quot;Extract&quot;:
        '''  Extracted text from Japanese document.
        '''  This action expends a little bit time.
        '''  Extracted text is show to another form.
        '''  Extracting from original resolution,so Zooming dose not affect,
        '''  but reversed up-down have effect on extracting.
        '''  Extracted portions are marked.
        '''
        '''  Vertical writing may be recognized horizontally.
        '''  in shch case as vertical and horizontal wri [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form2E() As String
            Get
                Return ResourceManager.GetString("help_form2E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージファイル読み取りの結果です
        '''読み取りエラーを修正してください
        '''長い行は折り返し表示されます
        '''&quot;Enter&quot;キーで行が分割され、改行マーク(⏎)の
        '''削除で行が連結されます
        '''
        '''&quot;かな変換&quot; ボタンを押すとメイン画面に
        '''かなテキストファイルが表示されます(多少時間がかかります)
        '''かな変換にあったては行末の改行１個は句読点、空白、
        '''括弧などで終わってないと次の行と連結して変換されます
        '''改行が２個以上の場合は連結されません
        '''変換に当たってはその点を意識してください
        '''
        '''マウス右ボタンからカット＆ペースト、検索と置換
        '''記号入力、辞書ファイルの利用、語句のショートカット入力ができます
        '''検索と置換および次を検索のショートカットは F3(上へ検索：Shift+F3)です
        '''
        '''(Form3) 2018/01/10
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form3() As String
            Get
                Return ResourceManager.GetString("help_form3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Kana-Kanji mixed text dialog.
        '''
        '''Text of Extracted from Document Image file
        '''Adjust mis-recognition in extraction.
        '''Long line is shown folded.
        '''User Enter key to split line,
        '''delete EndOfLine sign(⏎) to concatinate lines.
        '''
        '''&quot;Kana&quot; button translate kanji to Kana 
        '''and show result to main form.
        '''It take a little bit times.
        '''Lines not ended with puctuation including parenthesis or space
        '''are concatinated to the next line at translation.
        '''Concatination is not done if over 2 EndOfLine sign at end of line. 
        '''Cos [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form3E() As String
            Get
                Return ResourceManager.GetString("help_form3E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  画面フォント/印刷フォント:
        '''  フォントを設定します
        '''  左側のボタンを押すとフォント設定ダイアログが開きます
        '''  但し、スタイルは 標準、太字、斜体、太字　斜体 のみ選択できます
        '''  印刷用フォントを特に設定しない場合は
        '''  印刷フォント＝画面フォントにチェックを入れてください
        '''
        '''  以下４項目で機能キーF1～F12を指定しますが, F7,F8 は IME で カタカナ、
        '''  半角カタカナに使われているので使用しないほうがよいでしょう
        '''  スペースクリアーすると省略値 になります
        '''
        '''文字 置換キー:
        '''  大文字&lt;--&gt;小文字 置換に使用する機能キーを指定,  省略値 F5
        '''    &quot;あいうえおやゆよつわかけ&quot; &lt;--&gt; &quot;ぁぃぅぇぉゃゅょっゎゕゖ&quot;     ひらがな
        '''    &quot;アイウエオヤユヨツワカケ&quot; &lt;--&gt; &quot;ァィゥェォャュョッヮヵヶ&quot;     カタカナ
        '''    &quot;ｱｲｳｴｵﾔﾕﾖﾂ&quot;                &lt;--&gt; &quot;ｧｨｩｪｫｬｭｮｯ&quot;                    半角カタカナ
        '''
        '''  同じキー操作でイメージ読み取りで間違え易い字の置換も行います [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form5() As String
            Get
                Return ResourceManager.GetString("help_form5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Print Font/Screen Font:
        '''  Setup Font
        '''  Open FontDialog when IconButton pushed.
        '''  Choose Standard/Bold/Italic/Bold Italic only for FontStyle.
        '''
        '''  Set PFKey Number(F1&lt;--&gt;F12) for 4 items bellow.
        '''  F7 and F8 is not to be assigned because those are used by Japanese IME
        '''  to translate to Katakana and Hankaku-Katakana,
        '''  Back to default value when space cleared.
        '''
        '''Japanese Letter Replacement Key:
        '''  Set PFKey Number for replacement of Small and large Japanese Letter like as bellow.
        '''  Default is :F5.
        '''    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form5E() As String
            Get
                Return ResourceManager.GetString("help_form5E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;設定&quot;ダイアログの&quot;文字置換キー&quot;で変換する対象文字を
        '''このダイアログで拡張できます
        '''  &quot;変換列&quot;には2文字以上を指定してください
        '''  例） &apos;&quot;&lt;                    : (&apos;)--&gt;(&quot;)--&gt;(&lt;)--&gt;(&apos;) と巡回
        '''  変換します
        '''  /str1/str2/ 型式で文字列の変換も定義できます、逆の置換はしません
        '''  str1,str2 には空白文字も含められます
        '''  例) (F5は省略値の文字置換キーで設定ダイアログで変更可能)
        '''       -!                     : F5 で (-)--&gt;(!)--&gt;(-)
        '''       /:/.../                : F5 で (:)--&gt;(...)
        '''       /&quot;/&lt;/                  : F5 で (&quot;)--&gt;(&lt;)  
        '''       /&quot;/&gt;/     (+shift On)  : Shift+F5 で (&quot;)--&gt;(&lt;)
        '''       /、つ/う/              : F5 で (、つ)--&gt;(う)
        '''  &quot;設定&quot;ダイアログのヘルプで示 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form6() As String
            Get
                Return ResourceManager.GetString("help_form6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  This dialog expands replacement by &quot;Japanese Letter Replacement Key&quot;
        '''over default translation cases shown on &quot;Help&quot; of Setting dialog.
        '''  Specify at least 2 characters in &quot;Translation&quot; column.
        '''  e.g.) &apos;&quot;&lt;              : (&apos;)--&gt;(&quot;)--&gt;(&lt;)--&gt;(&apos;).
        '''  If char is defined duplicated to default cases shown on &quot;Help&quot; of &quot;Settings&quot;,
        '''  definition in this dialog is applied.
        '''  /str1/str2/ format allows string translation, no reverse replacemeny.
        '''  str1,str2 may contains space char.
        '''  e.g) (F5 is default functio key [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form6E() As String
            Get
                Return ResourceManager.GetString("help_form6E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号入力追加ダイアログ
        '''  記号入力の追加設定ができます
        '''  文字列には記号文字に限らず任意の文字列を設定できます
        '''  コメントの指定はなくてもかまいません
        '''  点字文字を設定する方法は、記号入力ダイアログのヘルプを
        '''  見てください
        '''
        '''(Form7) 2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form7() As String
            Get
                Return ResourceManager.GetString("help_form7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form7E) 
        '''Symbol Add Dialog
        '''  You can set any string.
        '''  Comment column may be null.
        '''  To set Braille string, see Help of Symbol Input dialog.
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form7E() As String
            Get
                Return ResourceManager.GetString("help_form7E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  探索と置換ダイアログ
        '''
        '''  かなテキスト画面と漢字テキスト画面と両方で使います。
        '''  どちらの画面に対するものかは画面の色で判定できます。
        '''  &quot;次の検索&quot;のショートカットは 省略値 F3 で、上へ検索は Shift+F3 です
        '''  &quot;置換&quot;のショートカットは 省略値 F2 で、上へ検索は Shift+F2 です
        '''  F3/F2 は&quot;設定&quot;で変更できます。
        '''
        '''(Form8) 2020/01/26
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form8() As String
            Get
                Return ResourceManager.GetString("help_form8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Find &amp; Replace Dialog
        '''
        '''  Available for both Kana-Kanji text and Kana text dialog.
        '''  The background colour indicates for which the dialog is.
        '''
        '''  Default shortcut key is F3 for FindNext, Shift+F3 for FindNext Upword.
        '''  Default shortcut key is F2 for Replace, Shift+F2 for Replace Upword.
        '''  Shortcut key is defined on &quot;Setting&quot; dialog.
        '''
        '''(Form8) 2020/01/26
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form8E() As String
            Get
                Return ResourceManager.GetString("help_form8E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Icon_i2k1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_i2k1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Icon_VBOCR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_VBOCR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt; 
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Resources_en_GB() As String
            Get
                Return ResourceManager.GetString("Resources_en_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ひらがな に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_HIRAGANA() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_HIRAGANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  漢字 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_KANJI() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_KANJI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  カタカナ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_KATAKANA() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_KATAKANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  小文字 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_KATAKANA_SMALL() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_KATAKANA_SMALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_KIGO() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_KIGO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文字種不明 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CHAR_TYPE_UNKNOWN() As String
            Get
                Return ResourceManager.GetString("STR_CHAR_TYPE_UNKNOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  複写 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_COPY() As String
            Get
                Return ResourceManager.GetString("STR_COPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  複写-貼り付け に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_COPYPASTE() As String
            Get
                Return ResourceManager.GetString("STR_COPYPASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  切り取り に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CUT() As String
            Get
                Return ResourceManager.GetString("STR_CUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  切り取り-貼り付け に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_CUTPASTE() As String
            Get
                Return ResourceManager.GetString("STR_CUTPASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  英文テキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ENGLISH_DOC() As String
            Get
                Return ResourceManager.GetString("STR_ENGLISH_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  英文読み取りテキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ENGLISH_DOC_EXTRACTED() As String
            Get
                Return ResourceManager.GetString("STR_ENGLISH_DOC_EXTRACTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラー({0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_ADDTRANS_ERRVALUE() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_ADDTRANS_ERRVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;;&quot; は使用できません({0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_DICTIONARY_ERRVALUE() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_DICTIONARY_ERRVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  辞書ファイルの {0} 行目にエラーがあります に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_DICTIONARY_FILE_LINE_FORMAT() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_DICTIONARY_FILE_LINE_FORMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  この辞書はファイルからロードしたものでは有りません、名前を付けて保存をしてください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_DICTIONARY_FILE_NO_SAVE_FILE() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_DICTIONARY_FILE_NO_SAVE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} 行目にエラーがあります、合計 {1} 行のエラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_DICTIONARY_ROW_IGNORED() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_DICTIONARY_ROW_IGNORED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  語句定義で有効になっていません(Ctrl+{0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_NOT_ENABLED_KEY() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_NOT_ENABLED_KEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号入力ダイアログで有効になっていません(Ctrl+{0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_NOT_ENABLED_KEY_SYMBOL() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_NOT_ENABLED_KEY_SYMBOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  語句定義に登録されていません(Ctrl+{0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_NOT_REGISTERED_KEY() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_NOT_REGISTERED_KEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号入力ダイアログに登録されていません(Ctrl+{0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_NOT_REGISTERED_KEY_SYMBOL() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_NOT_REGISTERED_KEY_SYMBOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  キーは1文字、また &quot;;&quot; は使用できません({0}) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_WORDS_ERRVALUE() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_WORDS_ERRVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルの {0} 行目にエラーがあります に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_WORDS_FILE_LINE_FORMAT() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_WORDS_FILE_LINE_FORMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  この定義はファイルからロードしたものでは有りません、名前を付けて保存をしてください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_WORDS_FILE_NO_SAVE_FILE() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_WORDS_FILE_NO_SAVE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} 行目にエラーがあります、合計 {1} 行のエラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_ERR_MSG_WORDS_ROW_IGNORED() As String
            Get
                Return ResourceManager.GetString("STR_ERR_MSG_WORDS_ROW_IGNORED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  辞書ファイル(*.dct)|*.dct|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_DICTIONARY() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_DICTIONARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージ(*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.tif;*.tiff)|*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.tif;*.tiff|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_IMAGE() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_IMAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな変換テキスト(*.txt;*.text)|*.txt;*.text|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_KANATEXT() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_KANATEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み取りテキスト(*.i2t;*.i2e)|*.i2t;*.i2e|テキスト(*.txt;*.text)|*.txt;*.text|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_KANJITEXT() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_KANJITEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  記号ファイル(*.sym)|*.sym|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_SYMBOL() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_SYMBOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変換の追加ファイル(*.trn)|*.trn|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_TCH() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_TCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  語句ファイル(*.wrd)|*.wrd|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_WORDS() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_WORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  太字 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FONT_BOLD() As String
            Get
                Return ResourceManager.GetString("STR_FONT_BOLD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  太字　斜体 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FONT_BOLD_ITALIC() As String
            Get
                Return ResourceManager.GetString("STR_FONT_BOLD_ITALIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  斜体 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FONT_ITALIC() As String
            Get
                Return ResourceManager.GetString("STR_FONT_ITALIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  標準 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FONT_STD() As String
            Get
                Return ResourceManager.GetString("STR_FONT_STD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルを開いてください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_INITIAL_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_INITIAL_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かなテキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_TITLE_KANA_FILE() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_TITLE_KANA_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな変換テキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_TITLE_KANJI2KANA_FILE() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_TITLE_KANJI2KANA_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージ文書 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM2_TITLE() As String
            Get
                Return ResourceManager.GetString("STR_FORM2_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストファイル に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM3_TITLE() As String
            Get
                Return ResourceManager.GetString("STR_FORM3_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読取りテキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM3_TITLE_RECEIVED() As String
            Get
                Return ResourceManager.GetString("STR_FORM3_TITLE_RECEIVED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  探索と置換 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM8_TITLE() As String
            Get
                Return ResourceManager.GetString("STR_FORM8_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変換の追加ファイルを読み込みました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_INFO_MSG_ADDTRANS_LOADED() As String
            Get
                Return ResourceManager.GetString("STR_INFO_MSG_ADDTRANS_LOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  辞書ファイルを読み込みました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_INFO_MSG_DICTIONARY_LOADED() As String
            Get
                Return ResourceManager.GetString("STR_INFO_MSG_DICTIONARY_LOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  語句ファイルを読み込みました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_INFO_MSG_WORDS_LOADED() As String
            Get
                Return ResourceManager.GetString("STR_INFO_MSG_WORDS_LOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルから設定 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_LOAD() As String
            Get
                Return ResourceManager.GetString("STR_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} --&gt; {1} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CHANGELETTER_ADDITIONAL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CHANGELETTER_ADDITIONAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変換しました {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CHANGELETTER_ADDITIONAL_STR() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CHANGELETTER_ADDITIONAL_STR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} : {1} --&gt; {2} : {3} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CHANGELETTERWRAP() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CHANGELETTERWRAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {0} : {1}  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CHANGELETTERWRAP_QUERY() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CHANGELETTERWRAP_QUERY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変更がありました、破棄しますか に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CONFIRM_DISCARD_DICTIONARY_UPDATE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CONFIRM_DISCARD_DICTIONARY_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変更がありました、破棄しますか に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CONFIRM_DISCARD_WORDS_UPDATE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CONFIRM_DISCARD_WORDS_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  既定を組み込みますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_CONFIRM_RESTORE_DEFAULT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_CONFIRM_RESTORE_DEFAULT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルの変更を破棄しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_DISCARD_UPDATE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_DISCARD_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  追加する位置（その行の前に追加）を選択してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_ADD_SELECT_LINE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_ADD_SELECT_LINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文字列が空白です に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_ADDDICTIONARY() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_ADDDICTIONARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  このファイルは処理済です に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_ALREADY_EXTRACTED() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_ALREADY_EXTRACTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  クリップボードにテキストデータがありません。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_CLIPBOARD_NOTEXT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_CLIPBOARD_NOTEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;{0}&quot; は濁音置換の対象ではありません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_DAKUON() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_DAKUON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージファイルからのテキスト読み取り失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_EXTRACT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_EXTRACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな/カナ変換に失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_FAILED_KANJI2KANA_CONV() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_FAILED_KANJI2KANA_CONV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索文字列は見つかりません ( に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_FIND_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_FIND_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索文字列が未設定です(スペース検索は &quot; &quot; を指定する) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_FIND_NULL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_FIND_NULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  機能キー:Fn (F1～F12)を指定してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_FUNCKEY() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_FUNCKEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな変換に失敗しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_KANA_CONV() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_KANA_CONV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな変換エラーがありました(&quot;Error&quot; で表示されています) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_KANACONV_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_KANACONV_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変更しようとしている転送先のフォ-ムが開いていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FORM_OPENED() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FORM_OPENED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルが見つかりません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索文字列はひとつも見つかりません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND_ALL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  現在位置:  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND_CPOS() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND_CPOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   行,カラム  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND_LINE_COL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND_LINE_COL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  現在位置:不明) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND_NO_CPOS() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND_NO_CPOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷フォント名に誤りがあります に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_PRINT_FONT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_PRINT_FONT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   ページが最後のページです に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_PRINT_PAGE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_PRINT_PAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル入力エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_READ() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_READ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  置換文字列が検索文字列と同じです に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_REPSTR_SAME() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_REPSTR_SAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  画面フォント名に誤りがあります に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SCR_FONT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SCR_FONT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  行が選択されていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SELECT_LINE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SELECT_LINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;{0}&quot; は置換キー（シフトキーなし）の 対象文字はありません。(設定のヘルプを見てください) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SMALL_LARGE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SMALL_LARGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;{0}&quot; は置換キー（＋シフトキー）の 対象文字はありません。  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SMALL_LARGE_OTHER() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SMALL_LARGE_OTHER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;;&quot; は使用できません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SPECIAL_KEY() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SPECIAL_KEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文字の指定がありません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_SPECIAL_KEY_NULL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_SPECIAL_KEY_NULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル出力エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_WRITE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_WRITE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ズーム失敗 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_ZOOM() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_ZOOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージからテキストを読取りました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_EXTRACTED() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_EXTRACTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  大小区別 なし、 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_FIND_CASE_INSENSE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_FIND_CASE_INSENSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  大小区別 あり、 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_FIND_CASE_SENSITIVE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_FIND_CASE_SENSITIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  下 方向、 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_FIND_DOWN() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_FIND_DOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  上 方向、 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_FIND_UP() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_FIND_UP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージ全体を保存: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_IMAGESAVE_FULL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_IMAGESAVE_FULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージの一部を保存: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_IMAGESAVE_PARTIAL() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_IMAGESAVE_PARTIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  変更がないので保存されませんでした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_NOT_SAVED_BY_NOUPDATE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_NOT_SAVED_BY_NOUPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_SAVED() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_SAVED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストを表示しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_SHOW_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_SHOW_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;{0}&quot; は大文字/小文字 置換の 対象文字です。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_SMALL_LARGE_TARGET() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_SMALL_LARGE_TARGET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  カタカナの送り仮名を認める設定を変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_KATAKANAOKURIGANA() As String
            Get
                Return ResourceManager.GetString("STR_MSG_KATAKANAOKURIGANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストが設定されていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_NO_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_NO_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルが存在します上書きしますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_REP_EXISTING() As String
            Get
                Return ResourceManager.GetString("STR_MSG_REP_EXISTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新規作成ファイル に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_TEXT_NEW() As String
            Get
                Return ResourceManager.GetString("STR_MSG_TEXT_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルエンコーディング={0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_TEXT_READ() As String
            Get
                Return ResourceManager.GetString("STR_MSG_TEXT_READ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  カーソルをテキスト内においてください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSR_WARN_CURSOR_POS() As String
            Get
                Return ResourceManager.GetString("STR_MSR_WARN_CURSOR_POS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  |新しいファイル| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWFILE() As String
            Get
                Return ResourceManager.GetString("STR_NEWFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  |新規作成| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWTEXT() As String
            Get
                Return ResourceManager.GetString("STR_NEWTEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  無題 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWTEXT_FILE() As String
            Get
                Return ResourceManager.GetString("STR_NEWTEXT_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  貼り付け に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_PASTE() As String
            Get
                Return ResourceManager.GetString("STR_PASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  上書き保存 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_SAVE() As String
            Get
                Return ResourceManager.GetString("STR_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  別名保存 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_SAVEAS() As String
            Get
                Return ResourceManager.GetString("STR_SAVEAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  転送 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_SEND() As String
            Get
                Return ResourceManager.GetString("STR_SEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み取り結果は空でした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property WARN_EXTRACTED_NULLSTR() As String
            Get
                Return ResourceManager.GetString("WARN_EXTRACTED_NULLSTR", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
